// Evolution tree for PLAGUE.
// Each evolution has:
//   id     — unique identifier
//   cat    — 'transmission' | 'symptoms' | 'abilities'
//   name   — display name
//   desc   — flavor / effect text
//   cost   — DNA cost
//   reqs   — list of prerequisite ids (all must be owned)
//   effects — accumulators applied to disease stats (see Game.recompute)
//   onEvolve — optional function called when evolution is purchased
const EVOLUTIONS = [
  // ───── Transmission ─────
  { id: 'air1', cat: 'transmission', name: 'Airborne 1', cost: 8, reqs: [],
    desc: 'Pathogen can survive briefly in the air. +Infectivity, slight severity.',
    effects: { trans_air: 1, infectivity: 3, severity: 1 } },
  { id: 'air2', cat: 'transmission', name: 'Airborne 2', cost: 12, reqs: ['air1'],
    desc: 'Pathogen lingers in airborne particles. Much higher airborne spread.',
    effects: { trans_air: 1, infectivity: 4, severity: 1 } },
  { id: 'water1', cat: 'transmission', name: 'Waterborne 1', cost: 8, reqs: [],
    desc: 'Survives in water supplies. +Infectivity in coastal & river nations.',
    effects: { trans_water: 1, infectivity: 3 } },
  { id: 'water2', cat: 'transmission', name: 'Waterborne 2', cost: 12, reqs: ['water1'],
    desc: 'Pathogen multiplies in standing water. Faster sea-borne spread.',
    effects: { trans_water: 1, infectivity: 3, severity: 1 } },
  { id: 'live1', cat: 'transmission', name: 'Livestock 1', cost: 8, reqs: [],
    desc: 'Cattle and swine transmit the pathogen. Big boost in rural nations.',
    effects: { trans_livestock: 1, infectivity: 2, ruralBoost: 0.15 } },
  { id: 'rodent', cat: 'transmission', name: 'Rodents', cost: 10, reqs: [],
    desc: 'Rats and mice carry the disease through sewers and cities.',
    effects: { trans_rodent: 1, infectivity: 2, urbanBoost: 0.15 } },
  { id: 'insect1', cat: 'transmission', name: 'Insects 1', cost: 8, reqs: [],
    desc: 'Mosquitos and fleas transmit the disease. Stronger in hot climates.',
    effects: { trans_insect: 1, infectivity: 2, hotBoost: 0.15 } },
  { id: 'insect2', cat: 'transmission', name: 'Insects 2', cost: 12, reqs: ['insect1'],
    desc: 'Insect carriers travel farther and bite more aggressively.',
    effects: { trans_insect: 1, infectivity: 3, hotBoost: 0.15 } },
  { id: 'bird', cat: 'transmission', name: 'Birds', cost: 10, reqs: [],
    desc: 'Migratory birds carry the pathogen across continents.',
    effects: { trans_bird: 1, infectivity: 2, crossSeaJump: 0.15 } },
  { id: 'blood', cat: 'transmission', name: 'Blood 1', cost: 10, reqs: [],
    desc: 'Spread through contaminated needles and blood. Boost in poor nations.',
    effects: { trans_blood: 1, infectivity: 2, poorBoost: 0.15 } },
  { id: 'bioaerosol', cat: 'transmission', name: 'Extreme Bioaerosol', cost: 22, reqs: ['air2', 'water2'],
    desc: 'A microscopic droplet phase. Dramatic global infectivity surge.',
    effects: { infectivity: 12, severity: 3, trans_air: 1, trans_water: 1 } },
  { id: 'zoonosis', cat: 'transmission', name: 'Extreme Zoonosis', cost: 18, reqs: ['live1', 'rodent'],
    desc: 'All animal carriers vector the disease aggressively.',
    effects: { infectivity: 8, severity: 2, trans_livestock: 1, trans_rodent: 1 } },

  // ───── Symptoms ─────
  { id: 'coughing',  cat: 'symptoms', name: 'Coughing',  cost: 3,  reqs: [],
    desc: 'A persistent cough makes airborne spread easier.',
    effects: { infectivity: 3, severity: 1 } },
  { id: 'sneezing',  cat: 'symptoms', name: 'Sneezing',  cost: 5,  reqs: ['coughing'],
    desc: 'Violent sneezing aerosolizes the pathogen.',
    effects: { infectivity: 4, severity: 1 } },
  { id: 'rash',      cat: 'symptoms', name: 'Rashes',    cost: 3,  reqs: [],
    desc: 'Itchy rashes lead to scratching and skin shedding.',
    effects: { infectivity: 2, severity: 2 } },
  { id: 'sweating',  cat: 'symptoms', name: 'Sweating',  cost: 4,  reqs: [],
    desc: 'Feverish sweating spreads pathogens through bodily fluids.',
    effects: { infectivity: 2, severity: 1, hotBoost: 0.05 } },
  { id: 'insomnia',  cat: 'symptoms', name: 'Insomnia',  cost: 5,  reqs: [],
    desc: 'Sleeplessness erodes the immune response.',
    effects: { infectivity: 2, severity: 2 } },
  { id: 'paranoia',  cat: 'symptoms', name: 'Paranoia',  cost: 8,  reqs: ['insomnia'],
    desc: 'Erratic behaviour slows the public health response.',
    effects: { severity: 4, cureResist: 0.05 } },
  { id: 'pulm1',     cat: 'symptoms', name: 'Pulmonary Edema',   cost: 10, reqs: [],
    desc: 'Fluid fills the lungs. Increased mortality.',
    effects: { lethality: 4, severity: 3 } },
  { id: 'pulm2',     cat: 'symptoms', name: 'Pulmonary Fibrosis', cost: 14, reqs: ['pulm1'],
    desc: 'Permanent scarring of lung tissue. High lethality.',
    effects: { lethality: 6, severity: 4 } },
  { id: 'hemor',     cat: 'symptoms', name: 'Hemorrhagic Shock',  cost: 16, reqs: ['pulm2'],
    desc: 'Catastrophic blood loss across the body.',
    effects: { lethality: 12, severity: 8 } },
  { id: 'organfail', cat: 'symptoms', name: 'Total Organ Failure', cost: 22, reqs: ['hemor'],
    desc: 'Every organ shuts down. Near-certain death.',
    effects: { lethality: 28, severity: 14 } },
  { id: 'necrosis',  cat: 'symptoms', name: 'Necrosis', cost: 14, reqs: ['rash'],
    desc: 'Tissue dies in great patches. Brutal symptoms and death.',
    effects: { lethality: 10, severity: 8, infectivity: -1 } },
  { id: 'coma',      cat: 'symptoms', name: 'Coma',     cost: 12, reqs: ['insomnia'],
    desc: 'Mask the worst symptoms. Slows detection and cure.',
    effects: { severity: -8, cureResist: 0.1 } },

  // ───── Abilities ─────
  { id: 'cold1',   cat: 'abilities', name: 'Cold Resistance 1', cost: 5,  reqs: [],
    desc: 'Pathogen survives cold climates better.',
    effects: { coldResist: 1 } },
  { id: 'cold2',   cat: 'abilities', name: 'Cold Resistance 2', cost: 10, reqs: ['cold1'],
    desc: 'Thrives in arctic conditions.',
    effects: { coldResist: 1 } },
  { id: 'heat1',   cat: 'abilities', name: 'Heat Resistance 1', cost: 5,  reqs: [],
    desc: 'Pathogen survives hot climates better.',
    effects: { heatResist: 1 } },
  { id: 'heat2',   cat: 'abilities', name: 'Heat Resistance 2', cost: 10, reqs: ['heat1'],
    desc: 'Thrives in desert and tropical conditions.',
    effects: { heatResist: 1 } },
  { id: 'envhard', cat: 'abilities', name: 'Environmental Hardening', cost: 12, reqs: ['cold1', 'heat1'],
    desc: 'Pathogen adapts to all climates.',
    effects: { coldResist: 1, heatResist: 1, severity: 1 } },
  { id: 'drug1',   cat: 'abilities', name: 'Drug Resistance 1', cost: 8,  reqs: [],
    desc: 'Develops resistance to common treatments. Slows cure research.',
    effects: { cureResist: 0.1 } },
  { id: 'drug2',   cat: 'abilities', name: 'Drug Resistance 2', cost: 14, reqs: ['drug1'],
    desc: 'Resists antivirals and prophylactic drugs.',
    effects: { cureResist: 0.15 } },
  { id: 'hard1',   cat: 'abilities', name: 'Genetic Hardening 1', cost: 12, reqs: [],
    desc: 'Tougher genome. Slows cure progress significantly.',
    effects: { cureResist: 0.2 } },
  { id: 'hard2',   cat: 'abilities', name: 'Genetic Hardening 2', cost: 16, reqs: ['hard1'],
    desc: 'Highly resilient genome. Major cure resistance.',
    effects: { cureResist: 0.25 } },
  { id: 'reshuf1', cat: 'abilities', name: 'Genetic ReShuffle 1', cost: 14, reqs: [],
    desc: 'Mutate to reset some cure progress.',
    effects: {}, onEvolve: (state) => { state.cure = Math.max(0, state.cure - 12); } },
  { id: 'reshuf2', cat: 'abilities', name: 'Genetic ReShuffle 2', cost: 18, reqs: ['reshuf1'],
    desc: 'A major mutation. Reset more cure progress.',
    effects: {}, onEvolve: (state) => { state.cure = Math.max(0, state.cure - 22); } },
];

const EVO_BY_ID = new Map(EVOLUTIONS.map((e) => [e.id, e]));
